### ISSUE TITLE
Application failed to start at client

### ISSUE THREAD

**Issue by arpanbose** [oktadeveloper/okta-spring-boot-authz-server-example#1]
I followed your process but facing an issue at the client application it's failed to start 

***************************
APPLICATION FAILED TO START
***************************

Description:

Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'clientRegistrationRepository' in 'OAuth2ClientRegistrationRepositoryConfiguration' not loaded because OAuth2 Clients Configured Condition registered clients is not available

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' in your configuration.

Process finished with exit code 0

**Comment by mraible** [comment]
@arpanbose Can you please try comparing your code to what this repo has? [SmartSynchorize](https://www.syntevo.com/smartsynchronize/) works well for comparing two different directories. My guess is you're using different versions of libraries than what we used.

**Comment by arpanbose** [comment]
I actually figure it out thanks by the way.
