### ISSUE TITLE
configuration in application.yml in auth server

### ISSUE THREAD

**Issue by Jovons** [oktadeveloper/okta-spring-boot-authz-server-example#2]
According to link [`oauth2login-boot-property-mappings`](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-boot-property-mappings), the folllowing configuration in application.yml:
`redirect-uri-template: http://localhost:8082/login/oauth2/code/`
should be:
`redirect-uri: http://localhost:8082/login/oauth2/code/`
see: [config file](https://github.com/oktadeveloper/okta-spring-boot-authz-server-example/blob/master/SpringBootOAuthClient/src/main/resources/application.yml)

versions may be related:
spring-boot-starter-security-2.2.6.RELEASE.jar
spring-security-oauth2-autoconfigure-2.2.6.RELEASE.jar
spring-security-oauth2-core-5.2.2.RELEASE.jar

**Comment by mraible** [comment]
Thanks for letting us know about this issue @Jovons! We really appreciate it. 😊
